#!/bin/sh

CC=cc
OBJECTS='main.o hello.o'
BIN=hello

case "$task" in
all)
    depends_on build
    ;;
build)
    depends_on $OBJECTS
    run $CC -o $BIN $OBJECTS
    ;;
*.o)
    src=${task%.o}.c
    depends_on "$src"
    run $CC -c -o "$task" "$src"
    ;;
clean)
    run rm -f *.o $BIN
    ;;
rebuild)
    depends_on clean build
    ;;
run)
    depends_on build
    run ./$BIN
    ;;
esac
